# Generated by Django 4.2.5 on 2023-09-15 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=70, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only alphabets are allowed in the name field.', regex='^[a-zA-Z]*$')]),
        ),
    ]
